# Generated by Django 5.2 on 2025-05-04 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('graduation_year', models.PositiveIntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('current_designation', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('skills', models.TextField(help_text='Comma-separated list of skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alumni',
                'verbose_name_plural': 'Alumni',
                'ordering': ['-graduation_year'],
            },
        ),
    ]
